namespace BeeBreeder.Common.Model.Genetics.Phenotype
{
    public enum Species
    {
        Forest,
        Meadows,
        Common,
        Cultivated,
        Noble,
        Majestic,
        Imperial,
        Diligent,
        Unweary,
        Industrious,
        Steadfast,
        Valiant,
        Heroic,
        Tropical,
        Exotic,
        Edenic,
        Rural,
        Austere,
        Sinister,
        Fiendish,
        Demonic,
        Modest,
        Frugal,
        Ender,
        Wintry, 
        Icy,
        Glacial,
        Marshy
    }
}